name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore TodoApi.sln
    - name: Build
      run: dotnet build TodoApi.sln --no-restore
    - name: Test
      run: dotnet test TodoApi.sln --no-build --verbosity normal
    - name: Publish
      run: dotnet publish TodoApi/TodoApi.csproj --configuration Release --output ./publish
    - name: Upload Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish/